(() => {
  'use strict';

  const state = { documents: [], views: [], query: '', category: 'All', sort: 'updated-desc', session: null, isOwner: false, activeId: null, deleteId: null, authMode: 'sign-in', theme: localStorage.getItem('brain-theme') || 'dark' };
  const $ = id => document.getElementById(id);
  const els = {
    gate: $('access-gate'), gateForm: $('access-form'), gateMessage: $('access-message'), gateSubmit: $('access-submit'), gateDescriptionWrap: $('access-description-wrap'), gateUsername: $('access-username'), gatePassword: $('access-password'), gateDescription: $('access-description'),
    grid: $('document-grid'), empty: $('empty-state'), count: $('result-count'), filters: $('category-filters'), search: $('search-input'), sort: $('sort-select'), reader: $('reader-dialog'), readerContent: $('reader-content'), editor: $('editor-dialog'), editorForm: $('document-form'), editorBody: $('editor-body'), editorTitle: $('document-title'), editorDesc: $('document-description'), editorCategory: $('document-category'), editorTags: $('document-tags'), editorPublished: $('document-published'), editorHeading: $('editor-title'), editorState: $('save-state'), editorMessage: $('editor-message'), imageInput: $('image-input'), confirm: $('confirm-dialog'), toast: $('toast-region'), setup: $('setup-banner'), heroStatus: $('hero-status'), authButton: $('auth-button'), newButton: $('new-document-button'), analytics: $('analytics'), analyticsButton: $('analytics-button'), analyticsBody: $('analytics-body'), analyticsEmpty: $('analytics-empty'), totalViews: $('total-views'), uniqueViewers: $('unique-viewers'), documentsViewed: $('documents-viewed')
  };
  const formatDate = value => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value));
  const formatDateTime = value => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
  const readingTime = doc => `${Math.max(1, Math.ceil(window.BrainSanitize.plainText(doc.body_html).split(/\s+/).filter(Boolean).length / 200))} min read`;
  function showToast(message, type = '') { const item = document.createElement('div'); item.className = `toast ${type ? `is-${type}` : ''}`; item.textContent = message; els.toast.appendChild(item); setTimeout(() => item.remove(), 3800); }
  function setTheme() { document.documentElement.dataset.theme = state.theme; localStorage.setItem('brain-theme', state.theme); }
  function filteredDocs() { const q = state.query.toLowerCase(); const docs = state.documents.filter(doc => { const matchesCategory = state.category === 'All' || doc.category === state.category; const haystack = [doc.title, doc.description, doc.category, ...(doc.tags || []), window.BrainSanitize.plainText(doc.body_html)].join(' ').toLowerCase(); return matchesCategory && (!q || haystack.includes(q)); }); return docs.sort((a, b) => state.sort === 'title-asc' ? a.title.localeCompare(b.title) : state.sort === 'created-desc' ? new Date(b.created_at) - new Date(a.created_at) : new Date(b.updated_at) - new Date(a.updated_at)); }
  function renderFilters() { const categories = ['All', ...new Set(state.documents.map(doc => doc.category).filter(Boolean))]; els.filters.replaceChildren(...categories.map(category => { const button = document.createElement('button'); button.className = `filter-button ${state.category === category ? 'is-active' : ''}`; button.type = 'button'; button.dataset.category = category; button.textContent = category; return button; })); }
  function card(doc) { const article = document.createElement('article'); article.className = 'document-card'; const top = document.createElement('div'); top.className = 'card-topline'; const category = document.createElement('span'); category.className = 'category-label'; category.textContent = doc.category; top.appendChild(category); if (doc.is_demo) { const sample = document.createElement('span'); sample.className = 'sample-label'; sample.textContent = 'Sample'; top.appendChild(sample); } article.appendChild(top); const title = document.createElement('h3'); title.textContent = doc.title; article.appendChild(title); const desc = document.createElement('p'); desc.textContent = doc.description || 'A page from the personal archive.'; article.appendChild(desc); const tags = document.createElement('div'); tags.className = 'card-tags'; (doc.tags || []).slice(0, 3).forEach(tag => { const chip = document.createElement('span'); chip.className = 'tag'; chip.textContent = `#${tag}`; tags.appendChild(chip); }); article.appendChild(tags); const footer = document.createElement('div'); footer.className = 'card-footer'; const meta = document.createElement('div'); meta.className = 'card-meta'; const date = document.createElement('span'); date.textContent = formatDate(doc.updated_at); const time = document.createElement('span'); time.textContent = readingTime(doc); meta.append(date, time); footer.appendChild(meta); const open = document.createElement('button'); open.className = 'card-arrow'; open.type = 'button'; open.dataset.action = 'open-reader'; open.dataset.id = doc.id; open.setAttribute('aria-label', `Read ${doc.title}`); open.textContent = '↗'; footer.appendChild(open); article.appendChild(footer); if (state.isOwner && !doc.is_demo) { const edit = document.createElement('button'); edit.className = 'text-link'; edit.type = 'button'; edit.dataset.action = 'edit-document'; edit.dataset.id = doc.id; edit.textContent = 'Edit page'; article.appendChild(edit); } return article; }
  function renderLibrary() { const docs = filteredDocs(); els.grid.replaceChildren(...docs.map(card)); els.empty.hidden = docs.length > 0; els.count.textContent = `${docs.length} ${docs.length === 1 ? 'page' : 'pages'}`; els.heroStatus.textContent = state.isOwner ? 'Owner desk unlocked' : `${state.documents.length} pages in the archive`; document.querySelectorAll('[data-action="new-document"]').forEach(button => { button.hidden = !state.isOwner; }); els.newButton.hidden = !state.isOwner; renderFilters(); }
  async function load() { if (!state.session) return; try { state.documents = await window.BrainData.listDocuments(); renderLibrary(); if (window.BrainData.localMode) { els.setup.hidden = false; els.setup.textContent = 'Temporary mode: accounts, pages, images, and reading history stay in this browser.'; } } catch (error) { els.heroStatus.textContent = 'Could not load the archive'; showToast(error.message || 'Could not load your documents.', 'error'); } }
  function renderBoard() { if (!state.isOwner) return; const events = state.views; els.totalViews.textContent = events.length; els.uniqueViewers.textContent = new Set(events.map(event => event.viewer_id)).size; els.documentsViewed.textContent = new Set(events.map(event => event.document_id)).size; els.analyticsBody.replaceChildren(...events.map(event => { const row = document.createElement('tr'); [event.viewer_username, event.viewer_description, event.document_title, formatDateTime(event.viewed_at)].forEach((value, index) => { const cell = document.createElement(index === 0 ? 'th' : 'td'); if (index === 0) cell.scope = 'row'; cell.textContent = value || '—'; row.appendChild(cell); }); return row; })); els.analyticsBody.closest('.analytics-table-wrap').hidden = events.length === 0; els.analyticsEmpty.hidden = events.length > 0; }
  async function refreshBoard() { if (!state.isOwner) return; try { state.views = await window.BrainData.listViewEvents(); renderBoard(); } catch (error) { showToast(error.message || 'Could not load the reading board.', 'error'); } }
  async function refreshOwner() { state.isOwner = Boolean(state.session?.user?.role === 'owner'); els.analytics.hidden = !state.isOwner; els.analyticsButton.hidden = !state.isOwner; els.authButton.textContent = state.session ? `Sign out (${state.session.user.username})` : 'Sign in'; renderLibrary(); if (state.isOwner) await refreshBoard(); }
  function openAuth(mode = 'sign-in') { if (state.session) return signOut(); setAuthMode(mode); els.gateUsername.focus(); }
  function setAuthMode(mode) { state.authMode = mode; const signUp = mode === 'sign-up'; document.querySelectorAll('[data-local-auth-mode]').forEach(button => button.classList.toggle('is-active', button.dataset.localAuthMode === mode)); els.gateDescriptionWrap.hidden = !signUp; els.gateDescription.required = signUp; els.gatePassword.autocomplete = signUp ? 'new-password' : 'current-password'; els.gateSubmit.textContent = signUp ? 'Create account' : 'Sign in'; els.gateMessage.textContent = ''; }
  function closeDialog(dialog) { if (dialog?.open) dialog.close(); if (![els.reader, els.editor, els.confirm].some(item => item.open)) document.body.classList.remove('modal-open'); }
  async function hydrateImages(container, documentId) { if (!documentId) return; try { const images = await window.BrainData.listImages(documentId); const lookup = new Map(images.map(image => [image.id, image])); container.querySelectorAll('img[data-image-id]').forEach(image => { const record = lookup.get(image.dataset.imageId); if (record) { image.src = record.url; image.alt = record.alt_text; } else image.remove(); }); } catch (error) { showToast('Some images could not be loaded.', 'error'); } }
  function reader(doc) { els.readerContent.replaceChildren(); const kicker = document.createElement('div'); kicker.className = 'reader-kicker'; kicker.textContent = `${doc.category}  /  ${formatDate(doc.updated_at)}`; els.readerContent.appendChild(kicker); const title = document.createElement('h1'); title.id = 'reader-title'; title.textContent = doc.title; els.readerContent.appendChild(title); const desc = document.createElement('p'); desc.className = 'reader-description'; desc.textContent = doc.description; els.readerContent.appendChild(desc); const meta = document.createElement('div'); meta.className = 'reader-meta'; meta.textContent = `${readingTime(doc)}  ·  ${(doc.tags || []).map(tag => `#${tag}`).join('  ')}`; els.readerContent.appendChild(meta); const body = document.createElement('div'); body.className = 'reader-body'; body.innerHTML = window.BrainSanitize.sanitize(doc.body_html); els.readerContent.appendChild(body); const actions = document.createElement('div'); actions.className = 'reader-actions'; const back = document.createElement('button'); back.className = 'button button-quiet'; back.type = 'button'; back.dataset.action = 'close-dialog'; back.dataset.dialog = 'reader-dialog'; back.textContent = '← Back to library'; actions.appendChild(back); const group = document.createElement('div'); group.className = 'reader-action-group'; const print = document.createElement('button'); print.className = 'button button-quiet'; print.type = 'button'; print.dataset.action = 'print'; print.textContent = 'Print'; group.appendChild(print); if (state.isOwner && !doc.is_demo) { const edit = document.createElement('button'); edit.className = 'button button-primary'; edit.type = 'button'; edit.dataset.action = 'edit-document'; edit.dataset.id = doc.id; edit.textContent = 'Edit page'; group.appendChild(edit); const remove = document.createElement('button'); remove.className = 'button button-danger'; remove.type = 'button'; remove.dataset.action = 'delete-document'; remove.dataset.id = doc.id; remove.textContent = 'Delete'; group.appendChild(remove); } actions.appendChild(group); els.readerContent.appendChild(actions); els.reader.showModal(); document.body.classList.add('modal-open'); hydrateImages(body, doc.id); }
  async function openReader(id) { try { const doc = await window.BrainData.getDocument(id); if (!doc) return showToast('That page is no longer available.', 'error'); state.activeId = id; reader(doc); void window.BrainData.recordDocumentView(doc.id).then(() => { if (state.isOwner) refreshBoard(); }).catch(() => {}); } catch (error) { showToast(error.message || 'Could not open this page.', 'error'); } }
  async function openEditor(id = null) { if (!state.isOwner) return openAuth(); let doc = null; if (id) doc = await window.BrainData.getDocument(id); window.BrainEditor.open(doc); if (doc) hydrateImages(els.editorBody, doc.id); }
  async function saveEditor(model) { try { window.BrainEditor.setMessage(''); window.BrainEditor.setSaving(true); let doc = await window.BrainData.saveDocument(model); window.BrainEditor.setId(doc.id); for (const pending of model.pendingFiles) { const image = await window.BrainData.uploadImage(pending.file, doc.id, pending.altText); model.bodyHtml = model.bodyHtml.replaceAll(`data-image-id="${pending.id}"`, `data-image-id="${image.id}"`); window.BrainEditor.replacePending(pending.id, image); } if (model.pendingFiles.length) doc = await window.BrainData.saveDocument({ ...model, id: doc.id }); window.BrainEditor.markSaved(); window.BrainEditor.close(true); showToast('Document saved.', 'success'); await load(); } catch (error) { window.BrainEditor.setSaving(false); window.BrainEditor.setMessage(error.message || 'Could not save this document.'); } }
  async function onAccessSubmit(event) { event.preventDefault(); const mode = state.authMode; const username = els.gateUsername.value.trim(); const password = els.gatePassword.value; els.gateMessage.textContent = 'Working…'; els.gateSubmit.disabled = true; try { if (mode === 'sign-up') await window.BrainAuth.signUp(username, password, els.gateDescription.value.trim()); else await window.BrainAuth.signIn(username, password); els.gateForm.reset(); showToast(window.BrainAuth.session?.user?.role === 'owner' ? 'Signed in. Your desk is ready.' : 'Signed in as a reader account.', window.BrainAuth.session?.user?.role === 'owner' ? 'success' : ''); } catch (error) { els.gateMessage.textContent = error.message || 'Could not sign in.'; } finally { els.gateSubmit.disabled = false; } }
  async function signOut() { try { await window.BrainAuth.signOut(); closeDialog(els.reader); closeDialog(els.editor); state.documents = []; state.views = []; showToast('Signed out. Sign in again to view the library.'); } catch (error) { showToast(error.message, 'error'); } }
  async function onAuthChange(session, event, error) { if (error) showToast('Could not restore your sign-in session.', 'error'); state.session = session; document.body.classList.toggle('is-authenticated', Boolean(session)); if (session) { await refreshOwner(); await load(); } else { state.documents = []; state.views = []; state.isOwner = false; els.analytics.hidden = true; els.analyticsButton.hidden = true; els.setup.hidden = true; els.authButton.textContent = 'Sign in'; renderLibrary(); } }
  async function init() { setTheme(); $('footer-year').textContent = new Date().getFullYear(); window.BrainEditor.init({ dialog: els.editor, form: els.editorForm, title: els.editorTitle, description: els.editorDesc, category: els.editorCategory, tags: els.editorTags, published: els.editorPublished, body: els.editorBody, heading: els.editorHeading, state: els.editorState, message: els.editorMessage }, { save: saveEditor, close: () => {} }); els.gateForm.addEventListener('submit', onAccessSubmit); window.BrainAuth.init(onAuthChange); els.search.addEventListener('input', event => { state.query = event.target.value; renderLibrary(); }); els.sort.addEventListener('change', event => { state.sort = event.target.value; renderLibrary(); }); document.addEventListener('click', handleClick); els.imageInput.addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; const alt = window.prompt('Describe this image for someone using a screen reader:'); if (alt === null) return; if (!alt.trim()) return showToast('Please add alt text before inserting the image.', 'error'); try { window.BrainEditor.addPending(file, alt.trim()); showToast('Image added to your draft.'); } catch (error) { showToast(error.message, 'error'); } event.target.value = ''; }); }
  async function handleClick(event) { const mode = event.target.closest('[data-local-auth-mode]'); if (mode) return setAuthMode(mode.dataset.localAuthMode); const filter = event.target.closest('[data-category]'); if (filter) { state.category = filter.dataset.category; return renderLibrary(); } const action = event.target.closest('[data-action]'); if (!action) return; const type = action.dataset.action; if (type === 'toggle-theme') { state.theme = state.theme === 'dark' ? 'light' : 'dark'; return setTheme(); } if (type === 'open-auth') return openAuth(); if (type === 'close-dialog') return closeDialog($(action.dataset.dialog)); if (type === 'new-document') return openEditor(); if (type === 'open-reader') return openReader(action.dataset.id); if (type === 'edit-document') { closeDialog(els.reader); return openEditor(action.dataset.id); } if (type === 'close-editor') return window.BrainEditor.close(); if (type === 'trigger-image') return els.imageInput.click(); if (type === 'insert-link') { const url = window.prompt('Paste a web link:'); if (url) { els.editorBody.focus(); document.execCommand('createLink', false, url); } return; } if (type === 'print') return window.print(); if (type === 'refresh-board') { document.querySelector('#analytics')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); return refreshBoard(); } if (type === 'clear-board') { if (!window.confirm('Clear all local reading history? This cannot be undone.')) return; try { await window.BrainData.clearViewEvents(); state.views = []; renderBoard(); showToast('Reading history cleared.', 'success'); } catch (error) { showToast(error.message, 'error'); } return; } if (type === 'delete-document') { state.deleteId = action.dataset.id; closeDialog(els.reader); els.confirm.showModal(); document.body.classList.add('modal-open'); return; } if (type === 'confirm-delete') { try { await window.BrainData.deleteDocument(state.deleteId); closeDialog(els.confirm); showToast('Document deleted.', 'success'); await load(); } catch (error) { showToast(error.message, 'error'); } } }
  init();
})();
